### ISSUE TITLE
This works for the vite dev server but how to you enable this for `vite preview`?

### ISSUE THREAD

**Issue by chaosprint** [chaosprint/vite-plugin-cross-origin-isolation#1]
This works for the vite dev server but how to you enable this for` vite preview`?

_Originally posted by @delebash in https://github.com/vitejs/vite/issues/3909#issuecomment-951482918_

**Comment by delebash** [comment]
Great how do you enable if for vite preview?

**Comment by chaosprint** [comment]
> Great how do you enable if for vite preview?

Hi, I am very busy with a DDL on Nov 9. I will look into it right after that.

**Comment by delebash** [comment]
Thank you. Cheers!

**Comment by chaosprint** [comment]
I actually don't use `preview` in my workflow. Perhaps a better way is to issue this in the Vite repo or ask Vite community.
