### ISSUE TITLE
can not run project after add this plugin

### ISSUE THREAD

**Issue by saviourdog** [chaosprint/vite-plugin-cross-origin-isolation#2]
![image](https://user-images.githubusercontent.com/22761043/146475469-333c76a6-2a45-4306-9d07-ece05ebce340.png)

**Comment by chaosprint** [comment]
Can you describe how we can recreate this issue?

I create a new Vue project, add this plugin and it works fine.

What I did is:
`npm init vite@latest`

Choose Vue.

`npm i`

`npm i -D vite-plugin-cross-origin-isolation`

Then, make the `vite.config.js` the same as what your screenshot shows.
